version: "3.7"
services:
  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: speedtest
    container_name: speedtest-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - speedtest

  nginx:
    image: nginx:alpine
    container_name: speedtest-nginx
    restart: unless-stopped
    ports:
      - 1069:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - speedtest

networks:
  speedtest:
    driver: bridge
